# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12063ac8ee8c321bf3b97d5822769955f76606d7860fa42b4c75c30d32d273b3b8a5e0f91892968ce04d50b18a0465697e6545d217a48ae95ce8c9b67eb0c2d7

test:
  secret_key_base: dc32511b043ecc7817f74a357de7b718f0920081c20add03f0667d02771dbca4bb3ff8889f1a68a58d5080af745033b35b6f3a017ac7b2e9b907ed669a2c74ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
